### ISSUE TITLE
showcase 

### ISSUE THREAD

**Issue by onkelhoy** [onkelhoy/web-components#37]
~ _needs further planning, to be updated here_ ~

**goals**: 
- [ ] work on GitHub pages 
- [ ] produce a view that can showcase each package's views 
- [x] should use a smart rendering system (need the router component) so we can use the SPA  (#38)
- [x] should work on reload - hash-based (#31)
- [ ] uses import maps (#31)
- [ ] designated route /showcase
